version: '3.7'

networks:
  backend:
    driver: bridge

services:
  nginx:
    build:
      context: docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "86:80"
      - "8443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/www/:/var/www/certbot/
        #      - ./data/certbot/conf/:/etc/nginx/ssl/
    depends_on:
      - php
      - db
    networks:
      - backend
        #  certbot:
        #    image: certbot/cerbot:latest
        # volumes:
        # - ./data/certbot/www/:/var/www/certbot/:rw
        #- ./data/certbot/conf/:/etc/letsencrypt/:rw

        #  certbot:
        #    image: certbot/cerbot:latest
        #    volumes:
        #      - ./docker/certbot/www/:/var/www/certbot/:rw
        #      - ./docker/certbot/conf/:/etc/letsencrypt/
        
  db:
    build:
      context: docker/mysql
    container_name: db
    #command: --lower_case_table_names=0
    restart: always
    tty: true    
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  php:
    build:
      context: docker/php-fpm
    container_name: php
    volumes:
      - ./src:/var/www
    restart: always
    ports:
      - "9000:9000"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100000000000
    depends_on:
      - db
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
